name: Is everything okay?
on: [push, pull_request]
jobs:
  iseverythingokay:
    name: Is everything okay?
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install OCaml
        run: brew install ocaml
      - name: Build the project
        run: cd ocaml/ && sh build.sh
      - name: Run the project and tests
        run: ./ocaml/a.out
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: Fichiers
          path: files/
