name: Is everything okay?
on: [push, pull_request]
jobs:
  iseverythingokay:
    name: Is everything okay?
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install OCaml
        run: brew install ocaml
      - name: Build the project
        run: cd ocaml/ && sh build.sh
      - name: Run the project and tests
        run: ./ocaml/a.out
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: Resultats
          path: |
            files/moi_ECB.png
            files/moi_CBC.png
            files/moi_OFB.png
            files/moi_CFB.png
            files/health_ECB.bin
            files/health_CBC.bin
            files/health_OFB.bin
            files/health_CFB.bin
            files/health_ECB_decrypted.json
            files/health_CBC_decrypted.json
            files/health_OFB_decrypted.json
            files/health_CFB_decrypted.json
